Empty State Registration
Xcov19/mycovidconnect pull request #151
Opened 2020-12-17 14:20 UTC by premalrupnur

2020-12-17 14:28 UTC, premalrupnur commented
[
![image](https://user-images.githubusercontent.com/55614144/102500316-313ea200-40a2-11eb-8f1e-f7dc697cc08d.png)
]
the page looks like above

2020-12-17 14:36 UTC, premalrupnur commented
I think I have messed up with code formatting

2020-12-18 03:05 UTC, codecakes requested changes
Ive requested changes. 

In general, the git commits for any JIRA task should follow smart-commits. use that: https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html

Run `npm eslint:github-action` and `npm fmt`

2020-12-18 03:05 UTC, codecakes commented on src/containers/Search.jsx
> +                <a href="ESP_DOMAIN:8090/auth0/login/auth0>">
ESP_PROXY_DOMAIN and ESP_PROXY_PORT

2020-12-18 03:05 UTC, codecakes commented on src/constants/index.js
> +	REACT_APP_ESP_DOMAIN:ESP_DOMAIN,
ive mentioned down 👇 where you've used to rename this;

2020-12-27 09:12 UTC, codecakes approved these changes
Pls make changes and merge

2020-12-27 09:12 UTC, codecakes commented on src/App.css
> +}
EOF line space @premalrupnur

2020-12-27 09:15 UTC, ksr89 approved these changes

2020-12-27 12:21 UTC, premalrupnur commented on src/constants/index.js
> +	REACT_APP_ESP_PROXY_PORT:ESP_PROXY_PORT
@Akul same names have to be given in .env right I'll make those changes

2020-12-27 12:30 UTC, merged