designed the UI form
Xcov19/mycovidconnect pull request #244
Opened 2021-12-23 17:47 UTC by GreatHayat

2021-12-23 19:28 UTC, codecakes commented on package.json
>          "react-scripts": "^4.0.0",
@GreatHayat can you take a merge from develop, test it once & push updates

2021-12-23 19:33 UTC, codecakes requested changes
left some comments

2021-12-23 19:33 UTC, codecakes commented on src/components/Login.jsx
> +  const { logout, user, isAuthenticated, isLoading } = useAuth0();
@GreatHayat run fmt once https://github.com/Xcov19/mycovidconnect/blob/7d9fe18e6e926015f49c8ba679eb7bffe42046e7/package.json#L46

2022-07-06 14:22 UTC, tim08094495757 commented
use MainHOC?

2022-09-07 20:12 UTC, codecakes commented
issue #233 is closed. no longer the solution desired.

2022-09-07 20:12 UTC, closed without merging