Feature/frontend/website content
Xcov19/mycovidconnect pull request #71
Opened 2020-09-26 02:03 UTC by vasynizami

Styled it as close as I could to the XD file specifications; for some reason the fonts in the XD file notes don't look the way the fonts look actually; the social media icons weren't provided

2020-09-26 07:51 UTC, codecakes requested changes
make sure 
- you've pulled latest changes from master and then push a commit.
- If you are working for a user story ticket number, fashion your future commits format like here: https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/

2020-09-26 07:51 UTC, codecakes commented on src/App.css
> +  /* width: 98%;
use double star for opening comment `/** like this */` ; this is for all css/scss/less files here.
if you are sprinkling comments add a `TODO(<github handle): <reason for the comment`;
Once necessary step has been taken, remove that comment

2020-09-26 07:51 UTC, codecakes commented on src/components/Footer.jsx
> +            <a href="https://forum.mycovidconnect.com/" title="Join Now">
open in new tab `add target="_blank"`

2020-09-26 07:51 UTC, codecakes commented on src/components/Footer.jsx
> +            <a href="https://forum.mycovidconnect.com/d/2-about-xcov19-rapid-action-patient-dispatch-solution">
all footer links open in new tab. make those changes everywhere

2020-09-26 07:51 UTC, codecakes commented on src/components/Footer.jsx
> +            <div className="social-media">
ask kemo for media kits, icon-logos for helpful, wprn, mattermore, jogl; opensource against covid et al, ive pasted the links to these on main whatsapp group; for the icons that kemo can provide, remove these icons and add those w/ necessary name and links

2020-09-26 07:51 UTC, codecakes commented on src/components/Footer.jsx
> +            <a href="#">Contact Us</a>
change the name to Media Presence

2020-09-26 07:51 UTC, codecakes commented on src/index.css
> +}
End of File new blank line

2020-09-26 08:02 UTC, codecakes requested changes
move as many src/fonts files out and use cdn instead; for instance, instead of src/fonts/lato/Lato-Bold.ttf
try to lookup if cdn sites can serve these media. you will find them here:
- https://cdnjs.com/libraries?q=montserrat (u can search more there)
- https://www.bootstrapcdn.com/fontawesome/
- https://www.cdnfonts.com/montserrat.font (search more fonts there as per requirements)
- choose individual font packs here: https://pagecdn.com/lib/easyfonts

This will incredibly reduce the site load time even before caching;

2020-09-26 08:19 UTC, codecakes requested changes
In chrome, if you toggle to responsive device toolbar, you'll see for the following modes, the rendering is out of place:
- 400 x 655 responsive portrait
- 360 x 640 (galaxy s5)
- 375 x 667 iPhone 6/7/8
- iphoneX 375 x 812, both portrait and landscape
- ipad and ipad pro, portrait

maybe you can ask neha/mallory for relevant screen mockups for the ones you need help on? rest feel free to fit as per your viewing;

2020-09-30 15:14 UTC, codecakes requested changes
Looks good but the modal does not pop on click. left comment. 
You can see the site behavior here: https://5f749a3e6ca6d40007cd2da6--dreamy-keller-b8ad36.netlify.app/#

2020-09-30 15:14 UTC, codecakes commented on src/components/Footer.jsx
> +              >
add `target="_blank" rel="noopener"` in all links we want the [user to open externally](https://mathiasbynens.github.io/rel-noopener/) wherever there is `target="_blank"`

Also Add a todo over here somewhere like this:
 `TODO(@vasynizami) create a common js script for external links asking for conset`
Idea is like:
```javascript
 () => {
  // suspends initial behavior and asks user consent Yes/No whether they want to navigate to external llink or not? if not suspends default behaviour else continues. 
}
```

2020-09-30 15:14 UTC, codecakes commented on src/components/Footer.jsx
> +              <img src={Helpful} alt="helpful-logo" />
@vasynizami did kemo not give out the links? Ask for relevant links as well and update

2020-09-30 15:14 UTC, codecakes commented on src/components/Nav.jsx
> +      {/* <script
why is this commented out? 
The modal does not pop up on clilck.

2020-09-30 15:19 UTC, codecakes requested changes
do a `git merge` from master branch first; some changes need to be merged back into your branch;

2020-10-02 18:00 UTC, andyderek reviewed
Where are we at on this one?  I am available to help if needed.

2020-10-03 08:19 UTC, codecakes commented
> Where are we at on this one? I am available to help if needed.

@andyderek pls feel free to take this up;

2020-10-04 14:06 UTC, codecakes commented
@vasynizami push new commits here. see: https://github.com/Xcov19/mycovidconnect/pull/102#pullrequestreview-501626725

2020-10-04 14:11 UTC, codecakes commented
@andyderek @vasynizami take a fresh merge from master as well

2020-10-07 19:39 UTC, closed without merging