Formatted README
Xcov19/mycovidconnect pull request #79
Opened 2020-09-29 15:45 UTC by MEME-MAN234

I have updated the README.md and added CONTRIBUTING.md

2020-09-29 20:52 UTC, codecakes requested changes
It's a very nice PR. some minor changes but overall nicely done!

2020-09-29 20:52 UTC, codecakes commented on README.md
> +This is a part of project XCoV19 which aims to to build a software that guides patients to the nearest hospital, while modeling the spread of the virus in order to better anticipate hospital needs. [
two "to"'s typo.

2020-09-29 20:52 UTC, codecakes commented on README.md
> +This is a part of project XCoV19 which aims to to build a software that guides patients to the nearest hospital, while modeling the spread of the virus in order to better anticipate hospital needs. [
https://www.covidsos.net is enough for the link, since subroutes may change in future.

2020-09-29 20:52 UTC, codecakes commented on README.md
> +### [ akshayparmar90 ](https://github.com/akshayparmar90)
@MEME-MAN234 add yourself. nicely done!

2020-09-29 20:53 UTC, codecakes reviewed
ill approve once minor edits are done. you may then merge;

2020-09-30 03:13 UTC, MEME-MAN234 commented
I have resolved them!

2020-09-30 05:28 UTC, MEME-MAN234 commented
@codecakes Please check my request now!

2020-09-30 07:32 UTC, codecakes approved these changes

2020-09-30 08:38 UTC, MEME-MAN234 commented
Can you merge this?

2020-09-30 13:02 UTC, MEME-MAN234 commented
@codecakes Do you want me to add something else?

2020-09-30 14:49 UTC, codecakes commented
@MEME-MAN234 go ahead, you should be able to merge this

2020-09-30 14:55 UTC, MEME-MAN234 commented
@codecakes No I am unable to this since I don't have write access to this repo

2020-09-30 16:13 UTC, MEME-MAN234 commented
@codecakes Can you merge this? Since I don't have write access to this repo I can't do this.

2020-09-30 18:50 UTC, codecakes commented
> @codecakes Can you merge this? Since I don't have write access to this repo I can't do this.

go ahead, you should be able to now

2020-10-01 02:37 UTC, MEME-MAN234 commented
@codecakes check the screenshot.
![x](https://user-images.githubusercontent.com/61042678/94759280-1458d380-03bd-11eb-8982-bac6af6330e6.png)

2020-10-01 02:40 UTC, merged