removed package lock from .gitnore, Bumped node-fetch for DOS vuln
Xcov19/mycovidconnect pull request #97
Opened 2020-10-02 17:27 UTC by kairb

2020-10-03 08:03 UTC, codecakes requested changes
@kairb  pls make the changes and get a fresh merge from master branch and then commit back. rest looks good.

2020-10-03 08:03 UTC, codecakes commented on .gitignore
> +.tern-port
add an EoF blank line

2020-10-09 13:18 UTC, codecakes commented
@Jasonwei1106 can u look into this and take this up? take a fresh merge from master and push commits?

2020-10-13 15:34 UTC, ksr89 approved these changes

2020-10-18 20:16 UTC, codecakes approved these changes
pls merge and add ur name under credits in README

2020-10-19 13:29 UTC, kairb commented
> pls merge and add ur name under credits in README

Please when ready as I don't have permissions

2020-10-22 07:30 UTC, codecakes commented
> > pls merge and add ur name under credits in README
> 
> Please when ready as I don't have permissions

pls take a fresh merge. you should be able to merge after that

2021-03-10 20:34 UTC, closed without merging